<a href="https://colab.research.google.com/github/VenkateshDas/legal_text_retrieval_coliee/blob/master/data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
import os 
os.chdir('/content/drive/My Drive/COLIEE Retrieval /COLIEE Dry Run Data /')

#Parse XML

In [3]:
import xml.etree.ElementTree as ET
import re
import pandas as pd

In [4]:
relevant_doc_file_path_old = '/content/drive/My Drive/COLIEE Retrieval /COLIEE2019-StatuteLaw-English Training Data/'

In [5]:
relevant_doc_file_path = '/content/drive/My Drive/COLIEE Retrieval /COLIEE Dry Run Data /COLIEE2020statute_data-English/train/'

In [6]:
def parse_xml(file_path):    
    pattern = re.compile('\\nArticle\s\d*\-?\d?\d?\d?') 

    PairID_arr= []
    text1_arr = []
    text2_arr = []
    label_arr = []
    article_numbers = []
    count = 0
    sum = 0
    for files in os.listdir(file_path):
        try: 

            if files.endswith('.xml'):
                print(files)
                count += 1
                xmlp = ET.XMLParser(encoding="utf-8")
                tree = ET.parse(file_path+files, parser = xmlp)
                root = tree.getroot()
                count_list = []
                for pair in root.findall('pair'):
                    
                    PairID = pair.get('id')
                    count_list.append(PairID)
                    PairID_arr.append(PairID)
                    
                    text1 = pair.find('t1').text
                    text1_arr.append(str(text1))

                    numbers = re.findall(pattern,text1)
                    article_numbers.append(numbers)
                    
                    text2 = pair.find('t2').text
                    text2_arr.append(str(text2))

                    Label = pair.get('label')
                    label_arr.append(Label)
                sum += len(count_list)
                print(len(count_list))
                print(count_list)
        except Exception as e: 
            print(e , files)
    print(count)
    print(sum)
    return PairID_arr, text1_arr , article_numbers , text2_arr , label_arr

In [7]:
PairID_arr, text1_arr , article_numbers , text2_arr , label_arr = parse_xml(relevant_doc_file_path)

riteval_H18_en.xml
36
['H18-1-1', 'H18-1-2', 'H18-1-3', 'H18-2-1', 'H18-2-2', 'H18-2-3', 'H18-2-4', 'H18-2-5', 'H18-3-2', 'H18-3-4', 'H18-9-1', 'H18-9-2', 'H18-9-3', 'H18-15-1', 'H18-15-2', 'H18-15-3', 'H18-15-4', 'H18-15-5', 'H18-20-1', 'H18-20-2', 'H18-20-3', 'H18-21-2', 'H18-21-3', 'H18-23-I', 'H18-23-U', 'H18-25-E', 'H18-26-1', 'H18-26-5', 'H18-27-U', 'H18-28-1', 'H18-28-2', 'H18-28-3', 'H18-28-4', 'H18-29-4', 'H18-29-5', 'H18-32-5']
riteval_H20_en.xml
41
['H20-2-A', 'H20-2-O', 'H20-3-2', 'H20-3-3', 'H20-3-5', 'H20-6-2', 'H20-6-5', 'H20-12-1', 'H20-12-2', 'H20-12-4', 'H20-12-5', 'H20-15-A', 'H20-15-I', 'H20-18-A', 'H20-18-U', 'H20-18-E', 'H20-18-O', 'H20-19-A', 'H20-19-I', 'H20-19-U', 'H20-19-E', 'H20-19-O', 'H20-22-1', 'H20-23-5', 'H20-24-5', 'H20-26-1', 'H20-26-2', 'H20-26-3', 'H20-26-5', 'H20-27-A', 'H20-27-I', 'H20-27-U', 'H20-27-E', 'H20-27-O', 'H20-28-A', 'H20-28-I', 'H20-28-U', 'H20-28-E', 'H20-28-O', 'H20-30-I', 'H20-30-O']
riteval_H19_en.xml
37
['H19-1-3', 'H19-4-I', 'H19-5-3', 'H19-6-A', 'H19-6-I', 'H19-6-O', 'H19-7-2', 'H19-8-A', 'H19-10-I', 'H19-10-O', 'H19-11-3', 'H19-11-5', 'H19-12-1', 'H19-12-3', 'H19-12-4', 'H19-12-5', 'H19-13-A', 'H19-13-I', 'H19-13-U', 'H19-13-E', 'H19-13-O', 'H19-14-1', 'H19-15-I', 'H19-16-1', 'H19-16-2', 'H19-16-3', 'H19-16-4', 'H19-16-5', 'H19-17-1', 'H19-17-2', 'H19-20-I', 'H19-26-I', 'H19-26-U', 'H19-26-O', 'H19-30-1', 'H19-30-3', 'H19-30-5']
riteval_H22_en.xml
47
['H22-1-A', 'H22-1-I', 'H22-3-A', 'H22-3-E', 'H22-4-A', 'H22-4-I', 'H22-4-E', 'H22-5-I', 'H22-5-U', 'H22-5-O', 'H22-8-I', 'H22-9-I', 'H22-9-O', 'H22-10-O', 'H22-11-1', 'H22-11-2', 'H22-11-5', 'H22-14-A', 'H22-14-I', 'H22-14-E', 'H22-14-O', 'H22-15-A', 'H22-15-U', 'H22-17-4', 'H22-18-I', 'H22-19-A', 'H22-19-O', 'H22-21-2', 'H22-21-4', 'H22-22-2', 'H22-23-A', 'H22-23-E', 'H22-23-O', 'H22-25-3', 'H22-26-A', 'H22-26-I', 'H22-26-U', 'H22-26-E', 'H22-27-1', 'H22-27-2', 'H22-27-3', 'H22-27-4', 'H22-27-5', 'H22-28-1', 'H22-28-2', 'H22-28-3', 'H22-28-4']
riteval_H25_en.xml
60
['H25-2-I', 'H25-2-U', 'H25-2-E', 'H25-2-O', 'H25-3-1', 'H25-3-3', 'H25-3-4', 'H25-3-5', 'H25-4-U', 'H25-6-E', 'H25-8-1', 'H25-8-3', 'H25-8-4', 'H25-8-5', 'H25-11-A', 'H25-11-U', 'H25-11-E', 'H25-11-O', 'H25-13-1', 'H25-13-2', 'H25-13-3', 'H25-13-4', 'H25-13-5', 'H25-14-A', 'H25-14-I', 'H25-14-U', 'H25-14-E', 'H25-15-4', 'H25-16-3', 'H25-16-4', 'H25-21-U', 'H25-21-E', 'H25-21-O', 'H25-22-1', 'H25-22-2', 'H25-22-3', 'H25-22-4', 'H25-23-I', 'H25-23-U', 'H25-23-O', 'H25-24-A', 'H25-24-I', 'H25-24-E', 'H25-24-O', 'H25-26-1', 'H25-26-2', 'H25-26-3', 'H25-26-4', 'H25-26-5', 'H25-27-1', 'H25-27-2', 'H25-27-4', 'H25-28-A', 'H25-29-A', 'H25-29-I', 'H25-29-U', 'H25-29-E', 'H25-29-O', 'H25-30-3', 'H25-30-4']
riteval_H24_en.xml
79
['H24-1-A', 'H24-1-U', 'H24-1-E', 'H24-2-1', 'H24-2-2', 'H24-2-4', 'H24-4-A', 'H24-4-I', 'H24-4-U', 'H24-4-E', 'H24-4-O', 'H24-5-1', 'H24-5-3', 'H24-5-4', 'H24-6-A', 'H24-6-I', 'H24-6-U', 'H24-7-A', 'H24-7-E', 'H24-7-O', 'H24-8-3', 'H24-8-5', 'H24-9-1', 'H24-9-4', 'H24-10-1', 'H24-10-2', 'H24-10-3', 'H24-10-4', 'H24-10-5', 'H24-11-1', 'H24-11-4', 'H24-12-1', 'H24-12-2', 'H24-12-3', 'H24-12-5', 'H24-14-A', 'H24-14-U', 'H24-15-1', 'H24-15-3', 'H24-15-4', 'H24-15-5', 'H24-16-1', 'H24-16-2', 'H24-16-3', 'H24-16-4', 'H24-16-5', 'H24-17-1', 'H24-17-2', 'H24-17-3', 'H24-17-4', 'H24-19-1', 'H24-20-A', 'H24-20-I', 'H24-20-U', 'H24-20-E', 'H24-20-O', 'H24-22-1', 'H24-22-3', 'H24-22-4', 'H24-22-5', 'H24-23-1', 'H24-23-3', 'H24-24-U', 'H24-25-1', 'H24-25-5', 'H24-27-A', 'H24-27-I', 'H24-27-E', 'H24-27-O', 'H24-28-1', 'H24-28-2', 'H24-28-3', 'H24-28-4', 'H24-28-5', 'H24-29-1', 'H24-29-3', 'H24-30-1', 'H24-30-2', 'H24-30-3']
riteval_H23_en.xml
41
['H23-1-2', 'H23-1-3', 'H23-1-4', 'H23-1-5', 'H23-2-A', 'H23-2-I', 'H23-2-E', 'H23-2-O', 'H23-3-A', 'H23-3-I', 'H23-4-U', 'H23-4-O', 'H23-5-1', 'H23-5-2', 'H23-5-3', 'H23-9-2', 'H23-9-3', 'H23-10-1', 'H23-10-2', 'H23-10-3', 'H23-10-4', 'H23-11-A', 'H23-11-I', 'H23-11-E', 'H23-11-O', 'H23-12-A', 'H23-12-U', 'H23-13-A', 'H23-13-I', 'H23-13-E', 'H23-17-1', 'H23-19-1', 'H23-19-5', 'H23-21-4', 'H23-23-A', 'H23-25-I', 'H23-25-U', 'H23-25-E', 'H23-25-O', 'H23-26-3', 'H23-29-2']
riteval_H21_en.xml
54
['H21-1-1', 'H21-1-2', 'H21-1-3', 'H21-1-4', 'H21-1-5', 'H21-3-1', 'H21-3-2', 'H21-3-4', 'H21-3-5', 'H21-5-3', 'H21-5-4', 'H21-7-5', 'H21-8-A', 'H21-8-O', 'H21-9-1', 'H21-9-2', 'H21-9-3', 'H21-9-4', 'H21-10-1', 'H21-10-2', 'H21-10-3', 'H21-10-5', 'H21-12-1', 'H21-12-2', 'H21-12-3', 'H21-13-A', 'H21-13-I', 'H21-13-U', 'H21-13-E', 'H21-13-O', 'H21-15-3', 'H21-19-A', 'H21-19-I', 'H21-19-U', 'H21-19-E', 'H21-20-2', 'H21-20-4', 'H21-21-1', 'H21-21-3', 'H21-21-4', 'H21-21-5', 'H21-22-5', 'H21-24-A', 'H21-24-I', 'H21-24-E', 'H21-24-O', 'H21-25-3', 'H21-25-4', 'H21-25-5', 'H21-26-A', 'H21-26-U', 'H21-26-O', 'H21-27-O', 'H21-29-A']
riteval_H26_en.xml
74
['H26-1-E', 'H26-1-G', 'H26-1-I', 'H26-2-A', 'H26-2-G', 'H26-3-G', 'H26-4-G', 'H26-5-C', 'H26-6-A', 'H26-10-1', 'H26-10-2', 'H26-10-3', 'H26-11-A', 'H26-11-E', 'H26-11-G', 'H26-11-I', 'H26-12-A', 'H26-12-C', 'H26-12-E', 'H26-12-G', 'H26-12-I', 'H26-13-A', 'H26-13-E', 'H26-13-G', 'H26-13-I', 'H26-14-E', 'H26-14-G', 'H26-14-I', 'H26-16-A', 'H26-16-C', 'H26-16-E', 'H26-16-I', 'H26-17-C', 'H26-18-1', 'H26-18-2', 'H26-18-4', 'H26-19-A', 'H26-19-C', 'H26-19-E', 'H26-19-G', 'H26-20-1', 'H26-20-2', 'H26-20-3', 'H26-20-4', 'H26-20-5', 'H26-22-1', 'H26-22-2', 'H26-22-3', 'H26-22-4', 'H26-23-A', 'H26-23-E', 'H26-23-G', 'H26-24-A', 'H26-24-E', 'H26-24-G', 'H26-24-I', 'H26-25-2', 'H26-25-3', 'H26-25-4', 'H26-25-5', 'H26-27-A', 'H26-27-C', 'H26-27-E', 'H26-27-I', 'H26-29-2', 'H26-36-A', 'H26-36-C', 'H26-36-E', 'H26-36-G', 'H26-36-I', 'H26-37-A', 'H26-37-C', 'H26-37-E', 'H26-37-G']
riteval_H30_en.xml
70
['H30-1-A', 'H30-2-I', 'H30-2-U', 'H30-4-A', 'H30-4-I', 'H30-4-U', 'H30-4-E', 'H30-4-O', 'H30-5-A', 'H30-5-U', 'H30-5-E', 'H30-6-A', 'H30-7-A', 'H30-7-I', 'H30-8-A', 'H30-8-I', 'H30-9-A', 'H30-9-I', 'H30-9-U', 'H30-11-U', 'H30-11-O', 'H30-12-E', 'H30-13-A', 'H30-13-I', 'H30-13-U', 'H30-13-E', 'H30-15-A', 'H30-15-I', 'H30-15-U', 'H30-15-E', 'H30-15-O', 'H30-16-A', 'H30-16-I', 'H30-16-O', 'H30-18-I', 'H30-18-U', 'H30-18-E', 'H30-19-A', 'H30-19-I', 'H30-19-U', 'H30-19-E', 'H30-20-A', 'H30-20-E', 'H30-20-O', 'H30-22-A', 'H30-22-I', 'H30-22-U', 'H30-22-E', 'H30-22-O', 'H30-23-A', 'H30-23-I', 'H30-23-O', 'H30-24-A', 'H30-24-U', 'H30-24-E', 'H30-24-O', 'H30-25-A', 'H30-26-A', 'H30-26-U', 'H30-26-E', 'H30-26-O', 'H30-28-I', 'H30-28-U', 'H30-28-E', 'H30-28-O', 'H30-29-I', 'H30-29-U', 'H30-29-E', 'H30-36-A', 'H30-36-O']
riteval_H29_en.xml
58
['H29-1-A', 'H29-1-I', 'H29-1-E', 'H29-1-O', 'H29-2-A', 'H29-2-I', 'H29-2-U', 'H29-2-O', 'H29-3-A', 'H29-3-I', 'H29-3-O', 'H29-4-A', 'H29-5-I', 'H29-5-U', 'H29-6-U', 'H29-6-E', 'H29-8-A', 'H29-9-A', 'H29-9-I', 'H29-9-U', 'H29-9-E', 'H29-9-O', 'H29-13-A', 'H29-13-I', 'H29-13-U', 'H29-13-E', 'H29-13-O', 'H29-14-U', 'H29-14-E', 'H29-16-A', 'H29-16-U', 'H29-17-A', 'H29-18-I', 'H29-18-E', 'H29-19-A', 'H29-21-E', 'H29-21-O', 'H29-23-A', 'H29-23-I', 'H29-23-U', 'H29-23-E', 'H29-23-O', 'H29-25-U', 'H29-25-E', 'H29-26-2', 'H29-26-5', 'H29-27-E', 'H29-27-O', 'H29-28-A', 'H29-28-E', 'H29-29-A', 'H29-29-I', 'H29-29-U', 'H29-29-E', 'H29-29-O', 'H29-33-A', 'H29-36-1', 'H29-37-U']
riteval_H27_en.xml
50
['H27-3-U', 'H27-3-E', 'H27-5-U', 'H27-5-E', 'H27-6-1', 'H27-6-2', 'H27-11-A', 'H27-11-I', 'H27-11-U', 'H27-11-E', 'H27-11-O', 'H27-12-E', 'H27-19-I', 'H27-19-U', 'H27-19-O', 'H27-20-A', 'H27-20-E', 'H27-21-E', 'H27-22-1', 'H27-22-3', 'H27-22-4', 'H27-23-A', 'H27-23-I', 'H27-23-U', 'H27-23-E', 'H27-23-O', 'H27-24-1', 'H27-24-2', 'H27-24-3', 'H27-24-4', 'H27-25-A', 'H27-26-A', 'H27-26-U', 'H27-27-A', 'H27-27-I', 'H27-27-U', 'H27-27-E', 'H27-27-O', 'H27-28-A', 'H27-28-U', 'H27-35-A', 'H27-35-I', 'H27-35-U', 'H27-35-E', 'H27-35-O', 'H27-36-A', 'H27-36-I', 'H27-36-U', 'H27-36-E', 'H27-36-O']
riteval_H28_en.xml
49
['H28-1-3', 'H28-1-4', 'H28-1-5', 'H28-2-1', 'H28-2-2', 'H28-3-1', 'H28-3-2', 'H28-3-3', 'H28-3-4', 'H28-3-5', 'H28-4-1', 'H28-4-2', 'H28-4-3', 'H28-4-4', 'H28-4-5', 'H28-11-1', 'H28-11-2', 'H28-11-3', 'H28-11-5', 'H28-12-1', 'H28-13-1', 'H28-13-2', 'H28-13-3', 'H28-13-4', 'H28-13-5', 'H28-14-1', 'H28-14-2', 'H28-14-3', 'H28-16-1', 'H28-16-2', 'H28-16-3', 'H28-16-4', 'H28-16-5', 'H28-17-1', 'H28-17-3', 'H28-17-5', 'H28-20-1', 'H28-22-1', 'H28-22-2', 'H28-22-4', 'H28-26-1', 'H28-26-2', 'H28-27-1', 'H28-27-2', 'H28-27-4', 'H28-28-1', 'H28-35-1', 'H28-35-2', 'H28-35-3']
13
696

In [8]:
def create_dataframe(PairID_arr, text1_arr , article_numbers , text2_arr):    
    dict_relevant = {'ID' : PairID_arr , 'Query' : text2_arr , 'Article_numbers' : article_numbers , 'Articles' : text1_arr }
    df_relevant = pd.DataFrame(dict_relevant)
    return df_relevant

In [9]:
df_relevant = create_dataframe(PairID_arr, text1_arr , article_numbers , text2_arr)
df_relevant.head()

        ID  ...                                           Articles
0  H18-1-1  ...  \nArticle 572\nEven if the seller makes a spec...
1  H18-1-2  ...  \nArticle 565\nThe provisions of the preceding...
2  H18-1-3  ...  \nArticle 568\n(1) The successful bidder at an...
3  H18-2-1  ...  \nArticle 697\n(1) A person that has begun to ...
4  H18-2-2  ...  \nArticle 698\nIf a manager engages in benevol...

[5 rows x 4 columns]

In [10]:
df_relevant_id_index = df_relevant.copy()
df_relevant_id_index.set_index('ID',inplace=True)

In [11]:
df_relevant.head()

        ID  ...                                           Articles
0  H18-1-1  ...  \nArticle 572\nEven if the seller makes a spec...
1  H18-1-2  ...  \nArticle 565\nThe provisions of the preceding...
2  H18-1-3  ...  \nArticle 568\n(1) The successful bidder at an...
3  H18-2-1  ...  \nArticle 697\n(1) A person that has begun to ...
4  H18-2-2  ...  \nArticle 698\nIf a manager engages in benevol...

[5 rows x 4 columns]

In [12]:
df_relevant_id_index.head()

                                                     Query  ...                                           Articles
ID                                                          ...
H18-1-1  \nA special provision that releases warranty c...  ...  \nArticle 572\nEven if the seller makes a spec...
H18-1-2  \nThere is a limitation period on pursuance of...  ...  \nArticle 565\nThe provisions of the preceding...
H18-1-3  \nA compulsory auction is also a sale, so warr...  ...  \nArticle 568\n(1) The successful bidder at an...
H18-2-1  \nIn cases where a person plans to prevent cri...  ...  \nArticle 697\n(1) A person that has begun to ...
H18-2-2  \nIn cases where an individual rescues another...  ...  \nArticle 698\nIf a manager engages in benevol...

[5 rows x 3 columns]

In [13]:
print(df_relevant_id_index.loc['H27-35-O',"Articles"])

Article 987
A person with a duty of testamentary gift (in this Section, a person who bears a duty to perform a testamentary gift) or any other interested party may give notice to a testamentary donee to the effect that acceptance or renunciation of a testamentary gift should be made within a specified period, fixing a period that is reasonable. In this case, if a donee does not indicate his/her intention to a person with a duty of testamentary gift within that period, the testamentary gift shall be deemed to have been accepted..

#Analysis on the Pairs

In [14]:
from collections import Counter 
from nltk.tokenize import wordpunct_tokenize
import pprint
import pickle

In [15]:
def find_character_length(df_relevant):
    '''
    This function is to find the length of the sequences in queries and articles.
    '''
    queries = df_relevant['Query']
    articles = df_relevant['Articles']
    pair_id = df_relevant['ID']

    query_length = []
    articles_length = []

    for i in range(len(queries)):
        query_length.append(len(queries[i]))
        articles_length.append(len(articles[i]))

    article_length_dict = dict(zip(pair_id,articles_length))
    query_length_dict = dict(zip(pair_id,query_length))

    return article_length_dict, query_length_dict, query_length, articles_length

In [16]:
def find_number_relevant_articles(df_relevant):
    '''
    This function is to find the number of relevant articles for a given query. 
    '''
    pair_id = df_relevant['ID']
    relevant_articles = df_relevant['Article_numbers']
    pair_id_list = []
    relevant_articles_list = []
    number_relevant_articles_list = []

    for i in range(len(pair_id)):
        pair_id_list.append(pair_id[i])
        relevant_articles_list.append(relevant_articles[i])
    
    for i in range(len(relevant_articles_list)):
        number_relevant_articles_list.append(len(relevant_articles_list[i]))
    

    number_relevant_articles_dict = dict(zip(pair_id_list,number_relevant_articles_list))
    relevant_articles_dict = dict(zip(pair_id_list,relevant_articles_list))
    
    return number_relevant_articles_dict,relevant_articles_dict ,pair_id_list,relevant_articles_list

In [17]:
def query_vocabulary(df_relevant):
    '''
    This function is used to create the vocabulary for the queries. 
    '''

    queries = df_relevant['Query']
    pair_id = df_relevant['ID']

    query_dict = dict(zip(df_relevant['ID'],df_relevant['Query']))

    query_tokens=[]

    for keys,values in query_dict.items():
        query_tokens.append(wordpunct_tokenize(values))

    query_tokens_dict = dict(zip(df_relevant['ID'],query_tokens))

    query_tokens_length = []
    query_all_tokens = []

    for keys,values in query_tokens_dict.items():
        query_tokens_length.append(len(values))
        for token in values: 
            query_all_tokens.append(token)

    
    query_tokens_length_dict = dict(zip(df_relevant['ID'],query_tokens_length))
    query_unique_tokens = set(query_all_tokens)
    query_unique_tokens_size = len(query_unique_tokens)

    return query_dict , query_tokens_dict , query_tokens_length_dict , query_unique_tokens, query_unique_tokens_size

In [18]:
def articles_vocabulary(df_relevant):
    '''
    This function is used to create the vocabulary for the articles. 
    '''

    articles = df_relevant['Articles']
    pair_id = df_relevant['ID']

    articles_dict = dict(zip(df_relevant['ID'],df_relevant['Articles']))

    articles_tokens=[]

    for keys,values in articles_dict.items():
        articles_tokens.append(wordpunct_tokenize(values))

    articles_tokens_dict = dict(zip(df_relevant['ID'],articles_tokens))

    articles_tokens_length = []
    articles_all_tokens = []

    for keys,values in articles_tokens_dict.items():
        articles_tokens_length.append(len(values))
        for token in values: 
            articles_all_tokens.append(token)
    
    articles_tokens_length_dict = dict(zip(df_relevant['ID'],articles_tokens_length))
    articles_unique_tokens = set(articles_all_tokens)
    articles_unique_tokens_size = len(articles_unique_tokens)
    return articles_dict , articles_tokens_dict ,articles_tokens_length_dict, articles_unique_tokens , articles_unique_tokens_size

In [19]:
def similar_word_vocabulary(articles_unique_tokens,query_unique_tokens):
    similar_word_vocab = articles_unique_tokens.intersection(query_unique_tokens)

    return similar_word_vocab , len(similar_word_vocab)

In [20]:
def concat_unique_tokens(articles_unique_tokens,query_unique_tokens):
    all_unique_tokens = articles_unique_tokens.union(query_unique_tokens)

    return all_unique_tokens , len(all_unique_tokens)

In [21]:
#articles referenced within articles 

def articles_ref_within_articles(df_relevant):
    '''
    This function is used to find the number of articles referenced within the articles. 
    '''

    article_pattern = re.compile(r'\sArticle\s\d\d?[^.,:\\n]?\-?\d?')

    articles_dict = dict(zip(df_relevant['ID'],df_relevant['Articles']))

    article_reference_dict = {}
    unique_article_reference_dict = {}
    for keys,values in articles_dict.items():
        numbers = re.findall(article_pattern,values[1:])
        article_numbers = []
        unique_article_numbers = []
        for number in numbers:
            if number.startswith('\n') == True:
                pass
            else: 
                article_numbers.append(number)
        unique_article_numbers = set(article_numbers)
        unique_article_reference_dict.update({keys:unique_article_numbers})
        article_reference_dict.update({keys:article_numbers})


    return article_reference_dict , unique_article_reference_dict

In [22]:
# Number of articles per query 

def articles_per_query(df_relevant):
    '''
    This function is used to determine the number of articles per query along with the average number of articles per query. 
    '''

    article_numbers_dict = dict(zip(df_relevant['ID'],df_relevant['Article_numbers']))
    articles_per_query_dict = {}
    more_articles_per_query_dict = {}
    less_articles_per_query_dict = {}
    articles = 0
    id = 0

    for keys,values in article_numbers_dict.items():
        number_articles_per_query = len(values)

        if number_articles_per_query >= 3 : 
            more_articles_per_query_dict.update({keys:number_articles_per_query})
        else: 
            less_articles_per_query_dict.update({keys:number_articles_per_query})

        articles_per_query_dict.update({keys:number_articles_per_query})

        articles += number_articles_per_query
        id += 1

    average_article_per_query = articles / id

    return articles_per_query_dict , average_article_per_query , more_articles_per_query_dict , less_articles_per_query_dict

In [23]:
#duplicate queries 

def detect_duplicate_queries(df_relevant):

    queries = df_relevant['Query']

    queries_counter = Counter(queries)

    unique_queries = set(queries)

    if len(queries) != len(unique_queries):
        print("The number of queries : ")
        print(len(queries))
        print("The unique queries : ")
        print(len(unique_queries))
        print("-"*50)
        pprint.pprint(queries_counter.most_common(5))

    else: 
        print("There are no duplicate queries")

In [24]:
#matching the titles to the relevant articles in the ground truth
def match_titles_relevant_article(df_relevant,file_path):

    article_title_dict = pickle.load(open(file_path, "rb"))

    article_numbers = df_relevant['Article_numbers']
    pair_id = df_relevant['ID']
    for i in range(len(article_numbers)):
        for number in article_numbers[i]:
            try: 
                # print(article_title_dict[number[1:]])
                if number[1:] in article_title_dict.keys():
                    continue
                else:
                    print("Article number not found in the Statute civil code text")
                    print(number[1:])
                    print(pair_id[i])
            except Exception as e:
                pass

In [25]:
df_relevant.head()

        ID  ...                                           Articles
0  H18-1-1  ...  \nArticle 572\nEven if the seller makes a spec...
1  H18-1-2  ...  \nArticle 565\nThe provisions of the preceding...
2  H18-1-3  ...  \nArticle 568\n(1) The successful bidder at an...
3  H18-2-1  ...  \nArticle 697\n(1) A person that has begun to ...
4  H18-2-2  ...  \nArticle 698\nIf a manager engages in benevol...

[5 rows x 4 columns]

### Without Normalisation of text

A descriptive analysis of the query and articles. 

- Finding the character length of each query and article 
- Finding the number of relevant articles for each query 
- Finding the number of tokens in each query and article 
- Finding the unique tokens for queries , articles and combined.

In [26]:
article_length_dict, query_length_dict, query_length, articles_length = find_character_length(df_relevant)

In [27]:
number_relevant_articles_dict, relevant_articles_dict ,pair_id_list,relevant_articles_list = find_number_relevant_articles(df_relevant)

In [28]:
query_dict , query_tokens_dict , query_tokens_length_dict , query_unique_tokens, query_unique_tokens_size = query_vocabulary(df_relevant)

In [29]:
articles_dict , articles_tokens_dict ,articles_tokens_length_dict, articles_unique_tokens , articles_unique_tokens_size = articles_vocabulary(df_relevant)

In [30]:
similar_word_vocab , similar_word_vocab_size = similar_word_vocabulary(articles_unique_tokens,query_unique_tokens)

In [31]:
all_unique_tokens , all_unique_tokens_size = concat_unique_tokens(articles_unique_tokens,query_unique_tokens)

To do :
- Number of articles referenced within each articles 
- Extracting the titles of the articles for each query. 
    - Finding the similar words in the title of the articles and query 
- ngram analysis of queries and articles (bi , tri , four) 
    - similar ngram matches in query and articles
- evaluating the Law2vec with regard to our dataset. 
    - Embedding the queries and articles with Law2vec , then projecting them in a 2d space. Finding the most similar words. 
- similar word matches in queries and articles 
    - exact word matches 
    - related word matches
- POS tagging of the articles and queries 
- Finding the most used tags in articles and queries 
- Finding the most recurring patterns of POS in articles and queries. 
- Similar tag patterns in query and article.
- Constituency parsing to find the noun phrases and verb phrases in a query and article 
    - Finding the amount of relevance for noun phrases in queries and articles. 
- Finding the presence and number of words that end in 'or' and 'ee' in both query and article. Along with the presence of its similar noun form . Example : "Obligor , Obligee" and its another similar noun form "Obligation".
- Find the amount of words that are not present in a lexicon , spell checker. 
- Finding the occurence of condition phrases in queries and articles. (Finding the number of occurences in a pair ) 
- Finding the occurence of constraints in queries and articles. (Finding the number of occurences in a pair )  
- Document clustering of articles and queries 
- topic modelling on queries and articles.

In [32]:
# Article numbers referenced within the articles are extracted and a dictionary with unique reference articles are also extracted.

article_reference_dict , unique_article_reference_dict = articles_ref_within_articles(df_relevant)
pprint.pprint(unique_article_reference_dict)

{'H18-1-1': {' Article 562', ' Article 565'},
 'H18-1-2': set(),
 'H18-1-3': {' Article 563', ' Article 565'},
 'H18-15-1': {' Article 372', ' Article 304'},
 'H18-15-2': set(),
 'H18-15-3': {' Article 2'},
 'H18-15-4': {' Article 472-4', ' Article 518'},
 'H18-15-5': set(),
 'H18-2-1': set(),
 'H18-2-2': set(),
 'H18-2-3': set(),
 'H18-2-4': {' Article 650'},
 'H18-2-5': set(),
 'H18-20-1': set(),
 'H18-20-2': set(),
 'H18-20-3': set(),
 'H18-21-2': {' Article 147',
              ' Article 148',
              ' Article 438',
              ' Article 439',
              ' Article 440',
              ' Article 441'},
 'H18-21-3': set(),
 'H18-23-I': set(),
 'H18-23-U': set(),
 'H18-25-E': set(),
 'H18-26-1': set(),
 'H18-26-5': set(),
 'H18-27-U': set(),
 'H18-28-1': set(),
 'H18-28-2': {' Article 446'},
 'H18-28-3': set(),
 'H18-28-4': {' Article 446'},
 'H18-29-4': set(),
 'H18-29-5': set(),
 'H18-3-2': set(),
 'H18-3-4': set(),
 'H18-32-5': set(),
 'H18-9-1': set(),
 'H18-9-2': set(),
 'H18-9-3': {' Article 306'},
 'H19-1-3': set(),
 'H19-10-I': {' Article 298'},
 'H19-10-O': set(),
 'H19-11-3': set(),
 'H19-11-5': set(),
 'H19-12-1': {' Article 351', ' Article 304', ' Article 296'},
 'H19-12-3': {' Article 325'},
 'H19-12-4': set(),
 'H19-12-5': set(),
 'H19-13-A': set(),
 'H19-13-E': set(),
 'H19-13-I': set(),
 'H19-13-O': set(),
 'H19-13-U': set(),
 'H19-14-1': set(),
 'H19-15-I': set(),
 'H19-16-1': set(),
 'H19-16-2': set(),
 'H19-16-3': set(),
 'H19-16-4': {' Article 383'},
 'H19-16-5': set(),
 'H19-17-1': set(),
 'H19-17-2': set(),
 'H19-20-I': set(),
 'H19-26-I': set(),
 'H19-26-O': set(),
 'H19-26-U': set(),
 'H19-30-1': {' Article 650'},
 'H19-30-3': set(),
 'H19-30-5': {' Article 645', ' Article 647'},
 'H19-4-I': set(),
 'H19-5-3': set(),
 'H19-6-A': set(),
 'H19-6-I': set(),
 'H19-6-O': set(),
 'H19-7-2': set(),
 'H19-8-A': set(),
 'H20-12-1': {' Article 304'},
 'H20-12-2': set(),
 'H20-12-4': {' Article 304'},
 'H20-12-5': {' Article 304'},
 'H20-15-A': {' Article 304'},
 'H20-15-I': set(),
 'H20-18-A': set(),
 'H20-18-E': set(),
 'H20-18-O': {' Article 446'},
 'H20-18-U': set(),
 'H20-19-A': set(),
 'H20-19-E': set(),
 'H20-19-I': set(),
 'H20-19-O': set(),
 'H20-19-U': set(),
 'H20-2-A': set(),
 'H20-2-O': set(),
 'H20-22-1': set(),
 'H20-23-5': set(),
 'H20-24-5': {' Article 196'},
 'H20-26-1': set(),
 'H20-26-2': {' Article 624'},
 'H20-26-3': {' Article 624'},
 'H20-26-5': set(),
 'H20-27-A': set(),
 'H20-27-E': set(),
 'H20-27-I': set(),
 'H20-27-O': set(),
 'H20-27-U': set(),
 'H20-28-A': set(),
 'H20-28-E': set(),
 'H20-28-I': set(),
 'H20-28-O': set(),
 'H20-28-U': set(),
 'H20-3-2': set(),
 'H20-3-3': {' Article 11\n',
             ' Article 17',
             ' Article 2',
             ' Article 602',
             ' Article 9'},
 'H20-3-5': {' Article 17'},
 'H20-30-I': set(),
 'H20-30-O': set(),
 'H20-6-2': set(),
 'H20-6-5': set(),
 'H21-1-1': set(),
 'H21-1-2': set(),
 'H21-1-3': set(),
 'H21-1-4': {' Article 11\n',
             ' Article 120',
             ' Article 17',
             ' Article 2',
             ' Article 602',
             ' Article 9'},
 'H21-1-5': {' Article 7\n'},
 'H21-10-1': set(),
 'H21-10-2': set(),
 'H21-10-3': set(),
 'H21-10-5': set(),
 'H21-12-1': set(),
 'H21-12-2': set(),
 'H21-12-3': set(),
 'H21-13-A': set(),
 'H21-13-E': set(),
 'H21-13-I': set(),
 'H21-13-O': set(),
 'H21-13-U': set(),
 'H21-15-3': set(),
 'H21-19-A': set(),
 'H21-19-E': {' Article 442'},
 'H21-19-I': set(),
 'H21-19-U': set(),
 'H21-20-2': set(),
 'H21-20-4': {' Article 466-3', ' Article 466'},
 'H21-21-1': set(),
 'H21-21-3': set(),
 'H21-21-4': set(),
 'H21-21-5': set(),
 'H21-22-5': set(),
 'H21-24-A': set(),
 'H21-24-E': set(),
 'H21-24-I': set(),
 'H21-24-O': set(),
 'H21-25-3': {' Article 650'},
 'H21-25-4': set(),
 'H21-25-5': {' Article 459-2'},
 'H21-26-A': {' Article 415'},
 'H21-26-O': set(),
 'H21-26-U': {' Article 620'},
 'H21-27-O': set(),
 'H21-29-A': set(),
 'H21-3-1': set(),
 'H21-3-2': set(),
 'H21-3-4': set(),
 'H21-3-5': set(),
 'H21-5-3': set(),
 'H21-5-4': set(),
 'H21-7-5': set(),
 'H21-8-A': set(),
 'H21-8-O': set(),
 'H21-9-1': set(),
 'H21-9-2': set(),
 'H21-9-3': set(),
 'H21-9-4': set(),
 'H22-1-A': set(),
 'H22-1-I': set(),
 'H22-10-O': set(),
 'H22-11-1': set(),
 'H22-11-2': set(),
 'H22-11-5': set(),
 'H22-14-A': set(),
 'H22-14-E': set(),
 'H22-14-I': set(),
 'H22-14-O': set(),
 'H22-15-A': set(),
 'H22-15-U': set(),
 'H22-17-4': set(),
 'H22-18-I': {' Article 446'},
 'H22-19-A': set(),
 'H22-19-O': set(),
 'H22-21-2': set(),
 'H22-21-4': set(),
 'H22-22-2': set(),
 'H22-23-A': {' Article 196'},
 'H22-23-E': set(),
 'H22-23-O': set(),
 'H22-25-3': set(),
 'H22-26-A': {' Article 624'},
 'H22-26-E': set(),
 'H22-26-I': set(),
 'H22-26-U': set(),
 'H22-27-1': set(),
 'H22-27-2': set(),
 'H22-27-3': set(),
 'H22-27-4': set(),
 'H22-27-5': {' Article 624'},
 'H22-28-1': set(),
 'H22-28-2': set(),
 'H22-28-3': set(),
 'H22-28-4': set(),
 'H22-3-A': set(),
 'H22-3-E': set(),
 'H22-4-A': {' Article 17'},
 'H22-4-E': set(),
 'H22-4-I': set(),
 'H22-5-I': set(),
 'H22-5-O': set(),
 'H22-5-U': set(),
 'H22-8-I': set(),
 'H22-9-I': set(),
 'H22-9-O': set(),
 'H23-1-2': set(),
 'H23-1-3': set(),
 'H23-1-4': set(),
 'H23-1-5': set(),
 'H23-10-1': set(),
 'H23-10-2': {' Article 202'},
 'H23-10-3': set(),
 'H23-10-4': set(),
 'H23-11-A': set(),
 'H23-11-E': {' Article 649', ' Article 650'},
 'H23-11-I': set(),
 'H23-11-O': {' Article 650'},
 'H23-12-A': set(),
 'H23-12-U': set(),
 'H23-13-A': {' Article 467'},
 'H23-13-E': {' Article 467'},
 'H23-13-I': set(),
 'H23-17-1': set(),
 'H23-19-1': set(),
 'H23-19-5': set(),
 'H23-2-A': set(),
 'H23-2-E': set(),
 'H23-2-I': {' Article 17'},
 'H23-2-O': set(),
 'H23-21-4': set(),
 'H23-23-A': set(),
 'H23-25-E': set(),
 'H23-25-I': {' Article 415'},
 'H23-25-O': {' Article 563', ' Article 565'},
 'H23-25-U': {' Article 415'},
 'H23-26-3': set(),
 'H23-29-2': set(),
 'H23-3-A': set(),
 'H23-3-I': set(),
 'H23-4-O': set(),
 'H23-4-U': set(),
 'H23-5-1': set(),
 'H23-5-2': set(),
 'H23-5-3': set(),
 'H23-9-2': set(),
 'H23-9-3': set(),
 'H24-1-A': {' Article 7\n', ' Article 876-9', ' Article 11', ' Article 17'},
 'H24-1-E': set(),
 'H24-1-U': {' Article 11\n',
             ' Article 17',
             ' Article 2',
             ' Article 602',
             ' Article 9'},
 'H24-10-1': set(),
 'H24-10-2': set(),
 'H24-10-3': set(),
 'H24-10-4': set(),
 'H24-10-5': set(),
 'H24-11-1': set(),
 'H24-11-4': set(),
 'H24-12-1': set(),
 'H24-12-2': set(),
 'H24-12-3': set(),
 'H24-12-5': set(),
 'H24-14-A': {' Article 298'},
 'H24-14-U': {' Article 351', ' Article 304', ' Article 296'},
 'H24-15-1': set(),
 'H24-15-3': set(),
 'H24-15-4': set(),
 'H24-15-5': set(),
 'H24-16-1': {' Article 2'},
 'H24-16-2': {' Article 472-4', ' Article 518'},
 'H24-16-3': set(),
 'H24-16-4': {' Article 398-4'},
 'H24-16-5': set(),
 'H24-17-1': set(),
 'H24-17-2': set(),
 'H24-17-3': {' Article 180'},
 'H24-17-4': {' Article 424'},
 'H24-19-1': set(),
 'H24-2-1': set(),
 'H24-2-2': set(),
 'H24-2-4': set(),
 'H24-20-A': {' Article 446'},
 'H24-20-E': set(),
 'H24-20-I': {' Article 446'},
 'H24-20-O': set(),
 'H24-20-U': {' Article 446'},
 'H24-22-1': set(),
 'H24-22-3': set(),
 'H24-22-4': set(),
 'H24-22-5': set(),
 'H24-23-1': {' Article 442'},
 'H24-23-3': set(),
 'H24-24-U': set(),
 'H24-25-1': set(),
 'H24-25-5': set(),
 'H24-27-A': set(),
 'H24-27-E': set(),
 'H24-27-I': set(),
 'H24-27-O': set(),
 'H24-28-1': set(),
 'H24-28-2': set(),
 'H24-28-3': set(),
 'H24-28-4': set(),
 'H24-28-5': set(),
 'H24-29-1': set(),
 'H24-29-3': set(),
 'H24-30-1': set(),
 'H24-30-2': {' Article 624'},
 'H24-30-3': set(),
 'H24-4-A': set(),
 'H24-4-E': set(),
 'H24-4-I': set(),
 'H24-4-O': set(),
 'H24-4-U': set(),
 'H24-5-1': set(),
 'H24-5-3': set(),
 'H24-5-4': set(),
 'H24-6-A': {' Article 128', ' Article 129'},
 'H24-6-I': set(),
 'H24-6-U': set(),
 'H24-7-A': {' Article 275'},
 'H24-7-E': {' Article 439'},
 'H24-7-O': {' Article 439'},
 'H24-8-3': set(),
 'H24-8-5': set(),
 'H24-9-1': {' Article 166'},
 'H24-9-4': {' Article 467'},
 'H25-11-A': set(),
 'H25-11-E': set(),
 'H25-11-O': set(),
 'H25-11-U': set(),
 'H25-13-1': set(),
 'H25-13-2': set(),
 'H25-13-3': set(),
 'H25-13-4': set(),
 'H25-13-5': {' Article 398-1'},
 'H25-14-A': set(),
 'H25-14-E': set(),
 'H25-14-I': set(),
 'H25-14-U': set(),
 'H25-15-4': {' Article 467'},
 'H25-16-3': set(),
 'H25-16-4': {' Article 424'},
 'H25-2-E': {' Article 11\n',
             ' Article 17',
             ' Article 2',
             ' Article 602',
             ' Article 9'},
 'H25-2-I': set(),
 'H25-2-O': {' Article 11\n'},
 'H25-2-U': set(),
 'H25-21-E': set(),
 'H25-21-O': set(),
 'H25-21-U': {' Article 467'},
 'H25-22-1': set(),
 'H25-22-2': set(),
 'H25-22-3': set(),
 'H25-22-4': set(),
 'H25-23-I': set(),
 'H25-23-O': set(),
 'H25-23-U': set(),
 'H25-24-A': {' Article 415'},
 'H25-24-E': set(),
 'H25-24-I': set(),
 'H25-24-O': {' Article 415', ' Article 563', ' Article 565'},
 'H25-26-1': set(),
 'H25-26-2': set(),
 'H25-26-3': set(),
 'H25-26-4': {' Article 624'},
 'H25-26-5': set(),
 'H25-27-1': set(),
 'H25-27-2': set(),
 'H25-27-4': set(),
 'H25-28-A': set(),
 'H25-29-A': set(),
 'H25-29-E': {' Article 624'},
 'H25-29-I': set(),
 'H25-29-O': set(),
 'H25-29-U': set(),
 'H25-3-1': {' Article 17'},
 'H25-3-3': set(),
 'H25-3-4': {' Article 120'},
 'H25-3-5': set(),
 'H25-30-3': set(),
 'H25-30-4': set(),
 'H25-4-U': set(),
 'H25-6-E': set(),
 'H25-8-1': set(),
 'H25-8-3': set(),
 'H25-8-4': set(),
 'H25-8-5': set(),
 'H26-1-E': {' Article 7\n'},
 'H26-1-G': {' Article 11\n',
             ' Article 17',
             ' Article 2',
             ' Article 602',
             ' Article 9'},
 'H26-1-I': {' Article 7\n', ' Article 876-9', ' Article 11', ' Article 17'},
 'H26-10-1': set(),
 'H26-10-2': set(),
 'H26-10-3': set(),
 'H26-11-A': set(),
 'H26-11-E': set(),
 'H26-11-G': set(),
 'H26-11-I': set(),
 'H26-12-A': set(),
 'H26-12-C': set(),
 'H26-12-E': set(),
 'H26-12-G': set(),
 'H26-12-I': set(),
 'H26-13-A': set(),
 'H26-13-E': set(),
 'H26-13-G': set(),
 'H26-13-I': set(),
 'H26-14-E': set(),
 'H26-14-G': set(),
 'H26-14-I': set(),
 'H26-16-A': set(),
 'H26-16-C': set(),
 'H26-16-E': set(),
 'H26-16-I': set(),
 'H26-17-C': set(),
 'H26-18-1': {' Article 439'},
 'H26-18-2': set(),
 'H26-18-4': {' Article 439'},
 'H26-19-A': set(),
 'H26-19-C': set(),
 'H26-19-E': set(),
 'H26-19-G': {' Article 459-2'},
 'H26-2-A': set(),
 'H26-2-G': set(),
 'H26-20-1': set(),
 'H26-20-2': set(),
 'H26-20-3': set(),
 'H26-20-4': set(),
 'H26-20-5': set(),
 'H26-22-1': set(),
 'H26-22-2': set(),
 'H26-22-3': set(),
 'H26-22-4': set(),
 'H26-23-A': set(),
 'H26-23-E': set(),
 'H26-23-G': {' Article 545'},
 'H26-24-A': set(),
 'H26-24-E': {' Article 551'},
 'H26-24-G': set(),
 'H26-24-I': set(),
 'H26-25-2': set(),
 'H26-25-3': set(),
 'H26-25-4': set(),
 'H26-25-5': set(),
 'H26-27-A': {' Article 645', ' Article 647', ' Article 624'},
 'H26-27-C': set(),
 'H26-27-E': {' Article 645', ' Article 647', ' Article 650'},
 'H26-27-I': {' Article 650'},
 'H26-29-2': set(),
 'H26-3-G': set(),
 'H26-36-A': {' Article 650'},
 'H26-36-C': set(),
 'H26-36-E': {' Article 304'},
 'H26-36-G': set(),
 'H26-36-I': {' Article 196'},
 'H26-37-A': set(),
 'H26-37-C': set(),
 'H26-37-E': set(),
 'H26-37-G': set(),
 'H26-4-G': set(),
 'H26-5-C': set(),
 'H26-6-A': set(),
 'H27-11-A': set(),
 'H27-11-E': set(),
 'H27-11-I': set(),
 'H27-11-O': set(),
 'H27-11-U': set(),
 'H27-12-E': {' Article 330'},
 'H27-19-I': set(),
 'H27-19-O': set(),
 'H27-19-U': set(),
 'H27-20-A': set(),
 'H27-20-E': set(),
 'H27-21-E': {' Article 533'},
 'H27-22-1': set(),
 'H27-22-3': set(),
 'H27-22-4': {' Article 649', ' Article 624', ' Article 650'},
 'H27-23-A': set(),
 'H27-23-E': set(),
 'H27-23-I': set(),
 'H27-23-O': set(),
 'H27-23-U': set(),
 'H27-24-1': {' Article 583', ' Article 196'},
 'H27-24-2': {' Article 594'},
 'H27-24-3': set(),
 'H27-24-4': {' Article 594'},
 'H27-25-A': set(),
 'H27-26-A': set(),
 'H27-26-U': set(),
 'H27-27-A': set(),
 'H27-27-E': {' Article 415'},
 'H27-27-I': {' Article 415'},
 'H27-27-O': set(),
 'H27-27-U': set(),
 'H27-28-A': set(),
 'H27-28-U': set(),
 'H27-3-E': set(),
 'H27-3-U': set(),
 'H27-35-A': {' Article 11\n',
              ' Article 17',
              ' Article 2',
              ' Article 602',
              ' Article 9'},
 'H27-35-E': set(),
 'H27-35-I': set(),
 'H27-35-O': set(),
 'H27-35-U': set(),
 'H27-36-A': set(),
 'H27-36-E': set(),
 'H27-36-I': set(),
 'H27-36-O': set(),
 'H27-36-U': {' Article 442', ' Article 459-2'},
 'H27-5-E': set(),
 'H27-5-U': set(),
 'H27-6-1': set(),
 'H27-6-2': set(),
 'H28-1-3': set(),
 'H28-1-4': set(),
 'H28-1-5': set(),
 'H28-11-1': set(),
 'H28-11-2': {' Article 351', ' Article 304', ' Article 296'},
 'H28-11-3': {' Article 298'},
 'H28-11-5': {' Article 330'},
 'H28-12-1': set(),
 'H28-13-1': {' Article 622-2'},
 'H28-13-2': set(),
 'H28-13-3': set(),
 'H28-13-4': {' Article 306'},
 'H28-13-5': set(),
 'H28-14-1': {' Article 351', ' Article 304', ' Article 296'},
 'H28-14-2': set(),
 'H28-14-3': set(),
 'H28-16-1': set(),
 'H28-16-2': set(),
 'H28-16-3': set(),
 'H28-16-4': {' Article 398-4'},
 'H28-16-5': set(),
 'H28-17-1': set(),
 'H28-17-3': set(),
 'H28-17-5': set(),
 'H28-2-1': set(),
 'H28-2-2': set(),
 'H28-20-1': set(),
 'H28-22-1': set(),
 'H28-22-2': {' Article 562', ' Article 565'},
 'H28-22-4': set(),
 'H28-26-1': {' Article 620'},
 'H28-26-2': set(),
 'H28-27-1': set(),
 'H28-27-2': set(),
 'H28-27-4': set(),
 'H28-28-1': set(),
 'H28-3-1': set(),
 'H28-3-2': set(),
 'H28-3-3': set(),
 'H28-3-4': set(),
 'H28-3-5': set(),
 'H28-35-1': set(),
 'H28-35-2': set(),
 'H28-35-3': set(),
 'H28-4-1': set(),
 'H28-4-2': set(),
 'H28-4-3': set(),
 'H28-4-4': set(),
 'H28-4-5': set(),
 'H29-1-A': set(),
 'H29-1-E': set(),
 'H29-1-I': set(),
 'H29-1-O': set(),
 'H29-13-A': {' Article 306'},
 'H29-13-E': {' Article 325'},
 'H29-13-I': set(),
 'H29-13-O': set(),
 'H29-13-U': set(),
 'H29-14-E': {' Article 520-2'},
 'H29-14-U': set(),
 'H29-16-A': set(),
 'H29-16-U': set(),
 'H29-17-A': set(),
 'H29-18-E': set(),
 'H29-18-I': set(),
 'H29-19-A': set(),
 'H29-2-A': {' Article 17'},
 'H29-2-I': {' Article 17'},
 'H29-2-O': set(),
 'H29-2-U': {' Article 17'},
 'H29-21-E': set(),
 'H29-21-O': set(),
 'H29-23-A': set(),
 'H29-23-E': set(),
 'H29-23-I': set(),
 'H29-23-O': set(),
 'H29-23-U': set(),
 'H29-25-E': set(),
 'H29-25-U': set(),
 'H29-26-2': set(),
 'H29-26-5': set(),
 'H29-27-E': set(),
 'H29-27-O': set(),
 'H29-28-A': {' Article 624'},
 'H29-28-E': set(),
 'H29-29-A': set(),
 'H29-29-E': set(),
 'H29-29-I': set(),
 'H29-29-O': {' Article 591'},
 'H29-29-U': set(),
 'H29-3-A': set(),
 'H29-3-I': set(),
 'H29-3-O': set(),
 'H29-33-A': {' Article 7\n'},
 'H29-36-1': set(),
 'H29-37-U': set(),
 'H29-4-A': set(),
 'H29-5-I': set(),
 'H29-5-U': set(),
 'H29-6-E': {' Article 275'},
 'H29-6-U': set(),
 'H29-8-A': set(),
 'H29-9-A': set(),
 'H29-9-E': set(),
 'H29-9-I': set(),
 'H29-9-O': set(),
 'H29-9-U': {' Article 703', ' Article 704', ' Article 242'},
 'H30-1-A': set(),
 'H30-11-O': {' Article 703', ' Article 704', ' Article 242'},
 'H30-11-U': set(),
 'H30-12-E': set(),
 'H30-13-A': set(),
 'H30-13-E': {' Article 196'},
 'H30-13-I': set(),
 'H30-13-U': set(),
 'H30-15-A': set(),
 'H30-15-E': set(),
 'H30-15-I': set(),
 'H30-15-O': {' Article 398-1'},
 'H30-15-U': set(),
 'H30-16-A': set(),
 'H30-16-I': set(),
 'H30-16-O': set(),
 'H30-18-E': set(),
 'H30-18-I': set(),
 'H30-18-U': set(),
 'H30-19-A': {' Article 459-2'},
 'H30-19-E': set(),
 'H30-19-I': set(),
 'H30-19-U': set(),
 'H30-2-I': set(),
 'H30-2-U': set(),
 'H30-20-A': set(),
 'H30-20-E': set(),
 'H30-20-O': set(),
 'H30-22-A': set(),
 'H30-22-E': {' Article 439'},
 'H30-22-I': set(),
 'H30-22-O': set(),
 'H30-22-U': {' Article 442'},
 'H30-23-A': set(),
 'H30-23-I': set(),
 'H30-23-O': set(),
 'H30-24-A': {' Article 551'},
 'H30-24-E': {' Article 196', ' Article 583', ' Article 580'},
 'H30-24-O': set(),
 'H30-24-U': set(),
 'H30-25-A': set(),
 'H30-26-A': set(),
 'H30-26-E': set(),
 'H30-26-O': set(),
 'H30-26-U': set(),
 'H30-28-E': set(),
 'H30-28-I': {' Article 650'},
 'H30-28-O': set(),
 'H30-28-U': {' Article 650'},
 'H30-29-E': set(),
 'H30-29-I': set(),
 'H30-29-U': set(),
 'H30-36-A': set(),
 'H30-36-O': set(),
 'H30-4-A': set(),
 'H30-4-E': set(),
 'H30-4-I': set(),
 'H30-4-O': set(),
 'H30-4-U': set(),
 'H30-5-A': set(),
 'H30-5-E': set(),
 'H30-5-U': set(),
 'H30-6-A': set(),
 'H30-7-A': set(),
 'H30-7-I': set(),
 'H30-8-A': set(),
 'H30-8-I': set(),
 'H30-9-A': set(),
 'H30-9-I': set(),
 'H30-9-U': set()}

In [33]:
articles_per_query_dict  , average_article_per_query ,  more_articles_per_query_dict , less_articles_per_query_dict  = articles_per_query(df_relevant)

# pprint.pprint(articles_per_query_dict)

print("-"* 50)
print("Average number of articles per query : " + str(average_article_per_query))

#Percentage of articles with more than 3 Articles per query 

print("Queries with more than or equal to 3 articles : "+str(len(more_articles_per_query_dict)))
print("Percantage of Queries with more than or equal to 3 articles : " + str(len(more_articles_per_query_dict)/696))

#Percentage of articles with less than 3 Articles per query 

print("Queries with less than or equal to 2 articles : " + str(len(less_articles_per_query_dict)))
print("Percantage of Queries with less than or equal to 2 articles : " + str(len(less_articles_per_query_dict)/696))

--------------------------------------------------
Average number of articles per query : 1.2974137931034482
Queries with more than or equal to 3 articles : 36
Percantage of Queries with more than or equal to 3 articles : 0.05172413793103448
Queries with less than or equal to 2 articles : 660
Percantage of Queries with less than or equal to 2 articles : 0.9482758620689655

In [34]:
file_path = '/content/drive/My Drive/COLIEE Retrieval /COLIEE Dry Run Data /article_title_dict.pkl'

match_titles_relevant_article(df_relevant,file_path)

Article number not found in the Statute civil code text
Article 987
H27-35-O

In [35]:
detect_duplicate_queries(df_relevant)

There are no duplicate queries

#Things to do 

1. Create a dataframe from the statute codes as planned
2. Create a dataframe from the ground truth as planned 
3. Prepare the preprocessing function that will be applied before further analysis.